#!/usr/bin/env python3
import argparse
from flair import FlairInputDataError
from flair.gtf_io import gtf_write_row
from flair.pycbio.hgdata.bed import BedReader, Bed
from flair.flair_bed import FlairBed


def main():
    parser = argparse.ArgumentParser(description='options')
    parser.add_argument('inputfile', type=str,
                        action='store', help='isoforms in bed format')
    parser.add_argument('--force', action='store_true', dest='force',
                        help='specify to not split isoform name by underscore into isoform and gene ids')
    parser.add_argument('--noCDS', action='store_true',
                        help='do not carry forward CDS from bed file (thickstart and thickend) to gtf file')
    parser.add_argument('--is_flair_bed', action='store_true',
                        help='specify if input is a bed12+ file generated by flair, will process extra columns an put as attributes in gtf')
    args = parser.parse_args()
    bed_to_gtf(query=args.inputfile, force=args.force, outputfile='/dev/stdout', useCDS=not args.noCDS, is_flair_bed=args.is_flair_bed)

def split_iso_gene(iso_gene):
    if '_chr' in iso_gene:
        iso = iso_gene[:iso_gene.rfind('_chr')]
        gene = iso_gene[iso_gene.rfind('_chr') + 1:]
    elif '_XM' in iso_gene:
        iso = iso_gene[:iso_gene.rfind('_XM')]
        gene = iso_gene[iso_gene.rfind('_XM') + 1:]
    elif '_XR' in iso_gene:
        iso = iso_gene[:iso_gene.rfind('_XR')]
        gene = iso_gene[iso_gene.rfind('_XR') + 1:]
    elif '_NM' in iso_gene:
        iso = iso_gene[:iso_gene.rfind('_NM')]
        gene = iso_gene[iso_gene.rfind('_NM') + 1:]
    elif '_NR' in iso_gene:
        iso = iso_gene[:iso_gene.rfind('_NR')]
        gene = iso_gene[iso_gene.rfind('_NR') + 1:]
    elif '_R2_' in iso_gene:
        iso = iso_gene[:iso_gene.rfind('_R2_')]
        gene = iso_gene[iso_gene.rfind('_R2_') + 1:]
    else:
        iso = iso_gene[:iso_gene.rfind('_')]
        gene = iso_gene[iso_gene.rfind('_') + 1:]
    return iso, gene

def _make_attrs(gene_id, transcript_id, bed, is_flair_bed, exon_number=None):
    """Build attrs dict for GTF output."""
    attrs = {'gene_id': gene_id, 'transcript_id': transcript_id}
    if exon_number is not None:
        attrs['exon_number'] = str(exon_number)
    if is_flair_bed:
        for name, val in bed.get_named_extra_attrs():
            attrs[name] = val
    return attrs

def bed_to_gtf(query, outputfile, force=False, useCDS=True, is_flair_bed=False):  # noqa: C901 - FIXME: reduce complexity
    outfile = open(outputfile, 'w')
    gene_to_records = {}
    gene_to_chrom_strand = {}
    my_bed_class = FlairBed if is_flair_bed else Bed
    for bed in BedReader(query, bedClass=my_bed_class):
        name = bed.name
        if '_' not in name and not force and not is_flair_bed:
            raise FlairInputDataError('Entry name should contain underscore-delimited transcriptid and geneid like so: \n'
                                      'ENST00000318842.11_ENSG00000156313.12 or a4bab8a3-1d28_chr8:232000\n'
                                      'So no GTF conversion was done. Please run identify_gene_isoform first\n'
                                      'for best results, or run with --force')

        if ';' in name:
            name = name.replace(';', ':')

        if is_flair_bed:
            transcript_id = name
            gene_id = bed.gene_id
        elif force is True:
            transcript_id, gene_id = name, name
        else:
            transcript_id, gene_id = split_iso_gene(name)

        if gene_id not in gene_to_records:
            gene_to_records[gene_id] = []
            gene_to_chrom_strand[gene_id] = (bed.chrom, bed.strand)

        attrs = _make_attrs(gene_id, transcript_id, bed, is_flair_bed)
        gene_to_records[gene_id].append(('transcript', bed.chrom, bed.chromStart, bed.chromEnd, bed.strand, attrs))

        for b, blk in enumerate(bed.blocks):
            exon_attrs = _make_attrs(gene_id, transcript_id, bed, is_flair_bed, exon_number=b)
            gene_to_records[gene_id].append(('exon', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
            if bed.thickStart != bed.thickEnd and (bed.thickStart != bed.chromStart or bed.thickEnd != bed.chromEnd) and useCDS:
                if bed.thickStart < blk.start and blk.end < bed.thickEnd:  # in CDS
                    gene_to_records[gene_id].append(('CDS', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                elif blk.end < bed.thickStart:  # fully left of CDS
                    if bed.strand == '+':
                        gene_to_records[gene_id].append(('5UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        gene_to_records[gene_id].append(('3UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                elif blk.start > bed.thickEnd:  # fully right of CDS
                    if bed.strand == '+':
                        gene_to_records[gene_id].append(('3UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        gene_to_records[gene_id].append(('5UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                elif blk.start <= bed.thickStart <= blk.end:  # left end of CDS in exon
                    if bed.strand == '+':
                        gene_to_records[gene_id].append(('5UTR', bed.chrom, blk.start, bed.thickStart, bed.strand, exon_attrs))
                        gene_to_records[gene_id].append(('start_codon', bed.chrom, bed.thickStart, bed.thickStart + 3, bed.strand, attrs))
                        gene_to_records[gene_id].append(('CDS', bed.chrom, bed.thickStart, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        gene_to_records[gene_id].append(('3UTR', bed.chrom, blk.start, bed.thickStart, bed.strand, exon_attrs))
                        gene_to_records[gene_id].append(('CDS', bed.chrom, bed.thickStart, blk.end, bed.strand, exon_attrs))
                elif blk.start <= bed.thickEnd <= blk.end:  # right end of CDS in exon
                    if bed.strand == '+':
                        gene_to_records[gene_id].append(('CDS', bed.chrom, blk.start, bed.thickEnd, bed.strand, exon_attrs))
                        gene_to_records[gene_id].append(('3UTR', bed.chrom, bed.thickEnd, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        gene_to_records[gene_id].append(('CDS', bed.chrom, blk.start, bed.thickEnd, bed.strand, exon_attrs))
                        gene_to_records[gene_id].append(('start_codon', bed.chrom, bed.thickEnd - 3, bed.thickEnd, bed.strand, attrs))
                        gene_to_records[gene_id].append(('5UTR', bed.chrom, bed.thickEnd, blk.end, bed.strand, exon_attrs))

    for gene_id, records in gene_to_records.items():
        chrom, strand = gene_to_chrom_strand[gene_id]
        gene_start = min(r[2] for r in records)
        gene_end = max(r[3] for r in records)
        gtf_write_row(outfile, chrom, 'FLAIR', 'gene', gene_start, gene_end, None, strand, None,
                      gene_id=gene_id)
        for feature, chrom, start, end, strand, attrs in records:
            gtf_write_row(outfile, chrom, 'FLAIR', feature, start, end, None, strand, None,
                          attrs=attrs)
    outfile.close()


if __name__ == "__main__":
    main()
