#!/usr/bin/env python3
import argparse
from flair import FlairInputDataError
from flair.gtf_io import gtf_write_row
from flair.iso_gene_id import split_iso_gene
from flair.pycbio.hgdata.bed import BedReader, Bed
from flair.flair_bed import FlairBed


def build_parser():
    desc = "converts isoforms in bed format to a gtf, written to stdout"
    parser = argparse.ArgumentParser(prog='bed_to_gtf', description=desc)
    parser.add_argument('inputfile', type=str, help='isoforms in bed format')
    parser.add_argument('--force', action='store_true',
                        help='do not split the isoform name by underscore into isoform and gene ids')
    parser.add_argument('--no_cds', action='store_true',
                        help='do not carry forward CDS from the bed file (thickstart and thickend) to the gtf')
    parser.add_argument('--is_flair_bed', action='store_true',
                        help='the input is a bed12+ file generated by flair; its extra columns are '
                             'processed and put as attributes in the gtf')
    return parser

def main():
    args = build_parser().parse_args()
    bed_to_gtf(query=args.inputfile, force=args.force, outputfile='/dev/stdout',
               useCDS=not args.no_cds, is_flair_bed=args.is_flair_bed)

def _add_record(records, record):
    """Record a feature, dropping an empty range.  A CDS or UTR piece is empty when the
    thick boundary sits exactly on an exon edge, and gtf_write_row writes start + 1, so
    an empty feature came out as start > end, which is not a GTF record and which
    flair's own parser rejects on re-read."""
    if record[2] < record[3]:
        records.append(record)


def _write_gene_records(outfile, gene_id, records):
    """The gene line and its features, one gene line per chrom and strand the gene id
    appears on.  A fusion gene has blocks on two chroms, and taking the first chrom
    with the min and max over all of them gave one line spanning both."""
    by_place = {}
    for record in records:
        by_place.setdefault((record[1], record[4]), []).append(record)
    for (chrom, strand), place_records in by_place.items():
        gtf_write_row(outfile, chrom, 'FLAIR', 'gene',
                      min(r[2] for r in place_records), max(r[3] for r in place_records),
                      None, strand, None, gene_id=gene_id)
        for feature, rec_chrom, start, end, rec_strand, attrs in place_records:
            gtf_write_row(outfile, rec_chrom, 'FLAIR', feature, start, end, None, rec_strand, None,
                          attrs=attrs)


def _make_attrs(gene_id, transcript_id, bed, is_flair_bed, exon_number=None):
    """Build attrs dict for GTF output."""
    attrs = {'gene_id': gene_id, 'transcript_id': transcript_id}
    if exon_number is not None:
        attrs['exon_number'] = str(exon_number)
    if is_flair_bed:
        for name, val in bed.get_named_extra_attrs():
            attrs[name] = val
    return attrs

def bed_to_gtf(query, outputfile, force=False, useCDS=True, is_flair_bed=False):  # noqa: C901 - FIXME: reduce complexity
    outfile = open(outputfile, 'w')
    gene_to_records = {}
    gene_to_chrom_strand = {}
    my_bed_class = FlairBed if is_flair_bed else Bed
    for bed in BedReader(query, bedClass=my_bed_class):
        name = bed.name
        if '_' not in name and not force and not is_flair_bed:
            raise FlairInputDataError('Entry name should contain underscore-delimited transcriptid and geneid like so: \n'
                                      'ENST00000318842.11_ENSG00000156313.12 or a4bab8a3-1d28_chr8:232000\n'
                                      'So no GTF conversion was done. Please run identify_gene_isoform first\n'
                                      'for best results, or run with --force')

        if ';' in name:
            name = name.replace(';', ':')

        if is_flair_bed:
            transcript_id = name
            gene_id = bed.gene_id
        elif force is True:
            transcript_id, gene_id = name, name
        else:
            transcript_id, gene_id = split_iso_gene(name)

        if gene_id not in gene_to_records:
            gene_to_records[gene_id] = []
            gene_to_chrom_strand[gene_id] = (bed.chrom, bed.strand)

        attrs = _make_attrs(gene_id, transcript_id, bed, is_flair_bed)
        _add_record(gene_to_records[gene_id], ('transcript', bed.chrom, bed.chromStart, bed.chromEnd, bed.strand, attrs))

        for b, blk in enumerate(bed.blocks):
            exon_attrs = _make_attrs(gene_id, transcript_id, bed, is_flair_bed, exon_number=b)
            _add_record(gene_to_records[gene_id], ('exon', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
            if bed.thickStart != bed.thickEnd and (bed.thickStart != bed.chromStart or bed.thickEnd != bed.chromEnd) and useCDS:
                if bed.thickStart < blk.start and blk.end < bed.thickEnd:  # in CDS
                    _add_record(gene_to_records[gene_id], ('CDS', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                elif blk.end < bed.thickStart:  # fully left of CDS
                    if bed.strand == '+':
                        _add_record(gene_to_records[gene_id], ('5UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        _add_record(gene_to_records[gene_id], ('3UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                elif blk.start > bed.thickEnd:  # fully right of CDS
                    if bed.strand == '+':
                        _add_record(gene_to_records[gene_id], ('3UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        _add_record(gene_to_records[gene_id], ('5UTR', bed.chrom, blk.start, blk.end, bed.strand, exon_attrs))
                elif blk.start <= bed.thickStart <= blk.end:  # left end of CDS in exon
                    if bed.strand == '+':
                        _add_record(gene_to_records[gene_id], ('5UTR', bed.chrom, blk.start, bed.thickStart, bed.strand, exon_attrs))
                        _add_record(gene_to_records[gene_id], ('start_codon', bed.chrom, bed.thickStart, min(bed.thickStart + 3, blk.end), bed.strand, attrs))
                        _add_record(gene_to_records[gene_id], ('CDS', bed.chrom, bed.thickStart, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        _add_record(gene_to_records[gene_id], ('3UTR', bed.chrom, blk.start, bed.thickStart, bed.strand, exon_attrs))
                        _add_record(gene_to_records[gene_id], ('CDS', bed.chrom, bed.thickStart, blk.end, bed.strand, exon_attrs))
                elif blk.start <= bed.thickEnd <= blk.end:  # right end of CDS in exon
                    if bed.strand == '+':
                        _add_record(gene_to_records[gene_id], ('CDS', bed.chrom, blk.start, bed.thickEnd, bed.strand, exon_attrs))
                        _add_record(gene_to_records[gene_id], ('3UTR', bed.chrom, bed.thickEnd, blk.end, bed.strand, exon_attrs))
                    elif bed.strand == '-':
                        _add_record(gene_to_records[gene_id], ('CDS', bed.chrom, blk.start, bed.thickEnd, bed.strand, exon_attrs))
                        _add_record(gene_to_records[gene_id], ('start_codon', bed.chrom, max(bed.thickEnd - 3, blk.start), bed.thickEnd, bed.strand, attrs))
                        _add_record(gene_to_records[gene_id], ('5UTR', bed.chrom, bed.thickEnd, blk.end, bed.strand, exon_attrs))

    for gene_id, records in gene_to_records.items():
        _write_gene_records(outfile, gene_id, records)
    outfile.close()


if __name__ == "__main__":
    main()
