#! /usr/bin/env python3


import argparse
import pysam
from copy import deepcopy
from flair.pycbio.hgdata.bed import BedReader
from flair.flair_bed import FlairBed
from flair.predictProductivity import translate_from_bed
from flair.isoform_data import make_big_bed, get_reverse_complement, translate_codon, COMPBASE
import vcfpy


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--allele_vcf', required=True, type=str,
                        help="vcf file from flair alleles")
    parser.add_argument('--allele_read_map', required=True, type=str,
                        help="tumor read map file from flair alleles")
    parser.add_argument('--allele_read_map_norm', type=str,
                        help="[optional] normal read map file from flair alleles")
    parser.add_argument('-o', '--output', default='flair',
                        help="output prefix. default: 'flair'")
    parser.add_argument('--genome',
                        type=str, required=True,
                        help='genome fasta file (used for making big bed)')
    parser.add_argument('--isoform_bed',
                        type=str, required=True,
                        help='isoform bed generated by FLAIR transcriptome')
    parser.add_argument('--iso_read_map',
                        type=str, required=True,
                        help='read map for tumor/single sample by FLAIR transcriptome or flair quantify')
    parser.add_argument('--iso_read_map_norm', type=str,
                        help='read map for normal (optional) sample by FLAIR transcriptome or flair quantify')
    parser.add_argument('--bam',
                        help='[optional] tumor bam - only provide if you want output of reads labeled with iso-allele groups (mostly for debugging)')
    parser.add_argument('--norm_bam',
                        help='[optional] normal bam - only provide if you want output of reads labeled with iso-allele groups (mostly for debugging)')
    parser.add_argument('--generate_map', default=False, action='store_true',
                        help='output read map of allele-isoform groups to read names')
    args = parser.parse_args()
    if (args.iso_read_map_norm is not None and args.allele_read_map_norm is None) or (args.iso_read_map_norm is None and args.allele_read_map_norm is not None):
        parser.error('If providing data for a normal sample, please provide both the iso read map and the allele read map')
    return args

def label_bam_file(bamname, output_name, read_to_allele_group):
    with pysam.AlignmentFile(bamname, 'rb') as bam:
        with pysam.AlignmentFile(output_name, 'wb', template=bam) as out:
            c, d = 0, 0
            for a in bam:
                if a.is_mapped and not a.is_secondary and not a.is_supplementary:
                    if a.query_name in read_to_allele_group:
                        iso, ps, ag = read_to_allele_group[a.query_name]
                        a.set_tag('PS', ps)
                        a.set_tag('AG', iso + '|' + ag)

                    else:
                        c += 1
                    d += 1
                out.write(a)
            print('unassigned reads:', c, '/', d)
    pysam.index(output_name)

def label_bam_files(bam, norm_bam, output, file_to_read_to_allele_group):
    label_bam_file(bam, output + '.tumor.bam', file_to_read_to_allele_group['t'])
    if norm_bam is not None:
        label_bam_file(norm_bam, output + '.normal.bam', file_to_read_to_allele_group['n'])

def get_bedisoform_info(bedisofile):
    isoforms = {}
    for bed in BedReader(bedisofile, bedClass=FlairBed):
        # ignoring fusion transcripts for now
        if bed.transcript_class != 'fusion':
            isoforms[bed.name] = bed
    return isoforms

def load_read_maps(read_map_files, read_to_data, index):
    for label, mapfile in read_map_files:
        for line in open(mapfile):
            data, reads = line.rstrip().split('\t', 1)
            for read in reads.split(','):
                if (label, read) not in read_to_data:
                    read_to_data[(label, read)] = [None, None]
                read_to_data[(label, read)][index] = data

def write_file_header(fh_counts, has_norm):
    outline = ['gene', 'source_isoform', 'phase_set', 'allele_group', 'allele_labeled_isoform', 'aaseq_id', 'tumor_counts']
    if has_norm is not None:
        outline.append('normal_counts')
    fh_counts.write('\t'.join(outline) + '\n')

def identify_cds_pos(isoform):
    cds_start_genomic, new_cds_start = None, 0
    if isoform.thickStart != isoform.thickEnd:
        if isoform.strand == '+':
            cds_start_genomic = isoform.thickStart
        else:
            cds_start_genomic = isoform.thickEnd
        for block in isoform.blocks:
            if isoform.strand == '+':
                if block.end < isoform.thickStart:
                    new_cds_start += block.end - block.start
                elif block.start <= isoform.thickStart:
                    new_cds_start += isoform.thickStart - block.start
                    break
            else:
                if block.start > isoform.thickEnd:
                    new_cds_start += block.end - block.start
                elif block.end >= isoform.thickEnd:
                    new_cds_start += block.end - isoform.thickEnd
    return cds_start_genomic, new_cds_start

def identify_nmd_pos(isoform):
    nmd_pos_genomic, new_nmd_pos = None, 0
    if isoform.thickStart != isoform.thickEnd:
        if len(isoform.blocks) > 1:
            if isoform.strand == '+':
                nmd_pos_genomic = isoform.blocks[-2].end
                new_nmd_pos = sum([b.end - b.start for b in isoform.blocks[:-1]])
                second_last_length = isoform.blocks[-2].end - isoform.blocks[-2].start
            else:
                nmd_pos_genomic = isoform.blocks[1].start
                new_nmd_pos = sum([b.end - b.start for b in isoform.blocks[1:]])
                second_last_length = isoform.blocks[1].end - isoform.blocks[1].start
            if second_last_length < 55:
                new_nmd_pos -= second_last_length
                if len(isoform.blocks) > 2:
                    nmd_pos_genomic = isoform.blocks[-3].end if isoform.strand == '+' else isoform.blocks[2].start
                else:
                    nmd_pos_genomic = isoform.blocks[-2].start if isoform.strand == '+' else isoform.blocks[1].end
            else:
                new_nmd_pos -= 55
                if isoform.strand == '+':
                    nmd_pos_genomic -= 55
                else:
                    nmd_pos_genomic += 55
    return nmd_pos_genomic, new_nmd_pos

def get_vars_overlapping_block(block, allele_group_vars):
    """Variants inside the block.  block.end is exclusive, and a variant at it used to
    be accepted, leaving adjust_seq_with_vars with an empty slice to index."""
    block_vars = []
    for chrom, pos, ref, alt in allele_group_vars:
        if block.start <= pos < block.end:
            block_vars.append((chrom, pos, ref, alt))
    return block_vars

def adjust_seq_with_vars(block, strand, block_vars, block_new_seq_complex, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos):
    # reverse sort so that adding vars doesn't impact index of next vars
    block_vars.sort(reverse=True)
    for chrom, pos, ref, alt in block_vars:
        before, var_seq, after = block_new_seq_complex[:pos - block.start], block_new_seq_complex[pos - block.start:(pos - block.start) + len(ref)], block_new_seq_complex[(pos - block.start) + len(ref):]
        block_new_seq_complex = before + [[x, var_seq[0][1], None] for x in alt] + after

        if cds_start_genomic is not None:
            if (strand == '+' and pos < cds_start_genomic) or (strand == '-' and pos > cds_start_genomic):
                new_cds_start += len(alt) - len(ref)
        if nmd_pos_genomic is not None:
            if (strand == '+' and pos < nmd_pos_genomic) or (strand == '-' and pos > nmd_pos_genomic):
                new_nmd_pos += len(alt) - len(ref)
    return block_new_seq_complex, new_cds_start, new_nmd_pos

def get_iso_seq_with_vars(isoform, allele_group_vars, genome, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos):
    this_iso_vars = []
    new_seq_complex = []
    for block in isoform.blocks:
        block_vars = get_vars_overlapping_block(block, allele_group_vars)
        block_ref_seq = genome.fetch(isoform.chrom, block.start, block.end).upper()
        block_new_seq_complex = [[block_ref_seq[x], block.start + x, None] for x in range(len(block_ref_seq))]

        block_new_seq_complex, new_cds_start, new_nmd_pos = adjust_seq_with_vars(block, isoform.strand, block_vars, block_new_seq_complex, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos)

        this_iso_vars.extend(block_vars)
        new_seq_complex.extend(block_new_seq_complex)
    if isoform.strand == '-':
        new_seq_complex = new_seq_complex[::-1]
        for i in range(len(new_seq_complex)):
            new_seq_complex[i][0] = COMPBASE[new_seq_complex[i][0]]

    return this_iso_vars, new_seq_complex, new_cds_start, new_nmd_pos

def identify_aaseq_with_vars(new_seq_complex, new_cds_start):
    aaseq = ''
    stop_index = None
    for i in range(new_cds_start, len(new_seq_complex), 3):
        # > not >=: at i + 3 == len the codon is complete and in range, and it is
        # often the stop, which the old bound dropped
        if i + 3 > len(new_seq_complex):
            break
        this_codon = ''.join([x[0] for x in new_seq_complex[i:i + 3]])
        # i == new_cds_start, not i == 0: i is 0 only for a transcript with no 5' UTR,
        # so every other transcript skipped the start codon requirement
        if i == new_cds_start and this_codon != 'ATG':
            break
        this_aa = translate_codon(this_codon)
        if this_aa == '_':
            stop_index = i + 2
            break
        aaseq += this_aa
        for j in range(i, i + 3):
            new_seq_complex[j][2] = this_aa
    return aaseq, stop_index

def update_isoform_productivity_aaseq(new_isoform, aaseq, new_seq_complex, stop_index, new_nmd_pos, aaseq_to_id, aaseq_count):
    if aaseq == '':
        new_isoform.productivity = 'NGO'
        new_isoform.aaseq_id = None
        new_isoform.thickStart = new_isoform.chromStart
        new_isoform.thickEnd = new_isoform.chromStart
    elif stop_index is None:
        new_isoform.productivity = 'NST'
        new_isoform.aaseq_id = None
        if new_isoform.strand == '+':
            new_isoform.thickEnd = new_isoform.chromEnd
        else:
            new_isoform.thickStart = new_isoform.chromStart
    else:
        if stop_index < new_nmd_pos:
            new_isoform.productivity = 'NMD'
            new_isoform.aaseq_id = None
        else:
            new_isoform.productivity = 'PRO'
            if aaseq not in aaseq_to_id:
                aaseq_to_id[aaseq] = f'FLP{aaseq_count:08d}'
                aaseq_count += 1
            new_isoform.aaseq_id = aaseq_to_id[aaseq]
        # update CDS on genome
        if new_isoform.strand == '+':
            new_isoform.thickEnd = new_seq_complex[stop_index][1]  # genomic pos at stop index
        else:
            new_isoform.thickStart = new_seq_complex[stop_index][1]
    return aaseq_count

def update_aaseq_no_vars(new_isoform, aaseq_to_id, genome, aaseq_count):
    aaseq = translate_from_bed(new_isoform, genome)
    if aaseq is not None:
        if aaseq not in aaseq_to_id:
            aaseq_to_id[aaseq] = f'FLP{aaseq_count:08d}'
            aaseq_count += 1
        new_isoform.aaseq_id = aaseq_to_id[aaseq]
    return aaseq_count

def make_var_isoform(isoform, transcript_class=None, allele_group=None, read_support=None, gene_tot=None):
    new_isoform = deepcopy(isoform)
    new_isoform.source_isoform = isoform.name
    if allele_group is not None and len(allele_group) > 0:
        new_isoform.name = isoform.name + '|' + allele_group
        new_isoform.allele_group = allele_group
    else:
        new_isoform.name = isoform.name + '||'
    if transcript_class is not None:
        new_isoform.transcript_class = transcript_class
    if read_support is not None:
        new_isoform.read_support = read_support
    if gene_tot is not None and read_support is not None:
        new_isoform.frac_support = read_support / gene_tot
    return new_isoform

def write_transcript_seq_no_vars(new_isoform, genome, fh_fa):
    transcript_seq = ''
    for block in new_isoform.blocks:
        transcript_seq += genome.fetch(new_isoform.chrom, block.start, block.end).upper()
    if new_isoform.strand == '-':
        transcript_seq = get_reverse_complement(transcript_seq)
    fh_fa.write(f'>{new_isoform.name}\n{transcript_seq}\n')

def write_counts_map(ol_base, out_name, iso_allele_reads, fh_counts, fh_map, fh_map_norm):
    ol_base.append(str(len(iso_allele_reads['t'])))
    if fh_map_norm is not None:
        ol_base.append(str(len(iso_allele_reads['n'])))
    fh_counts.write('\t'.join(ol_base) + '\n')

    if fh_map is not None:
        fh_map.write(f'{out_name}\t{",".join(sorted(iso_allele_reads["t"]))}\n')
        if fh_map_norm is not None:
            fh_map_norm.write(f'{out_name}\t{",".join(sorted(iso_allele_reads["n"]))}\n')

def write_iso_allele_counts_map(new_isoform, allele_group, iso_allele_reads, fh_counts, fh_map, fh_map_norm):
    ol_aaseq = new_isoform.aaseq_id if new_isoform.aaseq_id is not None else ''
    ps, ag = '', ''
    if len(allele_group) > 0:
        ps, ag = allele_group.split('|')[0], allele_group.split('|')[1]
    ol = [new_isoform.gene_id, new_isoform.source_isoform, ps, ag, new_isoform.name, ol_aaseq]
    write_counts_map(ol, new_isoform.name, iso_allele_reads, fh_counts, fh_map, fh_map_norm)

def write_out_new_isoform(isoform, allele_group, genome,
                          fh_bed, fh_fa, fh_counts, fh_map, fh_map_norm,
                          aaseq_count, aaseq_to_id, reads,
                          read_sup=None, gene_tot=None, transcript_class=None, aaseq_vars=None):
    new_isoform = make_var_isoform(isoform,
                                   transcript_class=transcript_class,
                                   allele_group=allele_group,
                                   read_support=read_sup,
                                   gene_tot=gene_tot)
    if aaseq_vars is None:
        aaseq_count = update_aaseq_no_vars(new_isoform, aaseq_to_id, genome, aaseq_count)
        write_transcript_seq_no_vars(new_isoform, genome, fh_fa)
    else:
        aaseq, new_seq_complex, stop_index, new_nmd_pos = aaseq_vars
        aaseq_count = update_isoform_productivity_aaseq(new_isoform, aaseq, new_seq_complex, stop_index, new_nmd_pos, aaseq_to_id, aaseq_count)
        transcript_seq = ''.join([x[0] for x in new_seq_complex])
        fh_fa.write(f'>{new_isoform.name}\n{transcript_seq}\n')
    new_isoform.write(fh_bed)
    write_iso_allele_counts_map(new_isoform, allele_group, reads, fh_counts, fh_map, fh_map_norm)
    return aaseq_count

def write_out_isoform_allele_groups(iso_allele_to_reads, allele_to_vars, isoforms, gene_to_tot_reads, genome,
                                    fh_bed, fh_fa, fh_counts, fh_map, fh_map_norm):
    aaseq_to_id, aaseq_count = {}, 1
    for (iso, allele), reads in iso_allele_to_reads.items():
        if iso is not None:
            isoform = isoforms[iso]
            if allele is None:  # isoform reads with no allelotype
                aaseq_count = write_out_new_isoform(isoform, '', genome,
                                                    fh_bed, fh_fa, fh_counts, fh_map, fh_map_norm,
                                                    aaseq_count, aaseq_to_id, reads,
                                                    read_sup=len(reads['t']), gene_tot=gene_to_tot_reads[isoform.gene_id]['t'])
            else:
                if allele not in allele_to_vars:  # no variants on this specific allele
                    aaseq_count = write_out_new_isoform(isoform, allele, genome,
                                                        fh_bed, fh_fa, fh_counts, fh_map, fh_map_norm,
                                                        aaseq_count, aaseq_to_id, reads,
                                                        read_sup=len(reads['t']), gene_tot=gene_to_tot_reads[isoform.gene_id]['t'],
                                                        transcript_class='with_vars')
                else:  # allele has vars, adjust bed
                    allele_vars = allele_to_vars[allele]
                    cds_start_genomic, new_cds_start = identify_cds_pos(isoform)
                    nmd_pos_genomic, new_nmd_pos = identify_nmd_pos(isoform)
                    this_iso_vars, new_seq_complex, new_cds_start, new_nmd_pos = get_iso_seq_with_vars(isoform, allele_vars, genome, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos)
                    # a non-coding isoform has no ORF; '' makes it NGO below rather
                    # than leaving the previous isoform's protein in scope
                    aaseq, stop_index = '', None
                    if cds_start_genomic is not None:
                        aaseq, stop_index = identify_aaseq_with_vars(new_seq_complex, new_cds_start)
                    aaseq_count = write_out_new_isoform(isoform, allele, genome,
                                                        fh_bed, fh_fa, fh_counts, fh_map, fh_map_norm,
                                                        aaseq_count, aaseq_to_id, reads,
                                                        read_sup=len(reads['t']), gene_tot=gene_to_tot_reads[isoform.gene_id]['t'],
                                                        transcript_class='with_vars',
                                                        aaseq_vars=(aaseq, new_seq_complex, stop_index, new_nmd_pos))
        else:  # no isoform - don't write out to bed, just write counts + map
            ol_base = ['', '', '', allele, '|' + allele, '']
            write_counts_map(ol_base, '|' + allele, reads, fh_counts, fh_map, fh_map_norm)
    return aaseq_to_id

def write_aaseq_key(output, aaseq_to_id):
    with open(output + '.aaseq.allelegroups.tsv', 'w') as fh:
        fh.write('aaseq_id\taaseq\n')
        for aaseq, id in aaseq_to_id.items():
            fh.write(f'{id}\t{aaseq}\n')

def load_iso_allele_read_maps(iso_read_map, iso_read_map_norm, allele_read_map, allele_read_map_norm):
    iso_read_maps, allele_read_maps = [('t', iso_read_map)], [('t', allele_read_map)]
    if iso_read_map_norm is not None:
        iso_read_maps.append(('n', iso_read_map_norm))
        allele_read_maps.append(('n', allele_read_map_norm))
    read_to_iso_allele = {}
    load_read_maps(iso_read_maps, read_to_iso_allele, 0)
    load_read_maps(allele_read_maps, read_to_iso_allele, 1)
    return read_to_iso_allele

def load_allele_to_vars(allele_vcf):
    allele_to_vars = {}
    for record in vcfpy.Reader.from_path(allele_vcf):
        # record.begin, not record.POS: flair alleles keeps variant positions 0-based
        # and writes POS as pos + 1, and every use below is 0-based genomic
        varinfo = [record.CHROM, record.begin, record.REF]
        varinfo += [alt.value for alt in record.ALT]  # there should always only be one alt per line
        for ag in record.INFO["AG"]:
            allele = f'{record.INFO["PS"]}|{ag}'
            if allele not in allele_to_vars:
                allele_to_vars[allele] = []
            allele_to_vars[allele].append(tuple(varinfo))
    return allele_to_vars

def update_gene_count(file_label, iso_allele, isoforms, gene_to_tot_reads):
    if iso_allele[0] is not None:  # has isoform
        gene = isoforms[iso_allele[0]].gene_id
        if gene not in gene_to_tot_reads:
            gene_to_tot_reads[gene] = {'t': 0, 'n': 0}
        gene_to_tot_reads[gene][file_label] += 1

def get_group_label(iso_allele):
    if iso_allele[1] is None:
        group_label = iso_allele[0] + '||'
    elif iso_allele[0] is None:
        group_label = '|' + iso_allele[1]
    else:
        group_label = iso_allele[0] + '|' + iso_allele[1]
    return group_label

def reorganize_iso_alleles(read_to_iso_allele, isoforms):
    gene_to_tot_reads = {}
    iso_allele_to_reads = {}
    file_to_read_to_group = {'t': {}, 'n': {}}
    for file_label, read in read_to_iso_allele:
        iso_allele = tuple(read_to_iso_allele[(file_label, read)])
        group_label = get_group_label(iso_allele)
        file_to_read_to_group[file_label][read] = tuple(group_label.split('|'))
        if iso_allele not in iso_allele_to_reads:
            iso_allele_to_reads[iso_allele] = {'t': [], 'n': []}
        iso_allele_to_reads[iso_allele][file_label].append(read)
        update_gene_count(file_label, iso_allele, isoforms, gene_to_tot_reads)

    return iso_allele_to_reads, file_to_read_to_group, gene_to_tot_reads

def getvariants():
    args = parse_args()
    print('loading read maps and gene data')

    allele_to_vars = load_allele_to_vars(args.allele_vcf)
    isoforms = get_bedisoform_info(args.isoform_bed)
    read_to_iso_allele = load_iso_allele_read_maps(args.iso_read_map, args.iso_read_map_norm, args.allele_read_map, args.allele_read_map_norm)

    iso_allele_to_reads, file_to_read_to_group, gene_to_tot_reads = reorganize_iso_alleles(read_to_iso_allele, isoforms)

    print('grouping alleles by isoform and getting protein predictions')
    with pysam.FastaFile(args.genome) as genome:
        with open(args.output + '.isoalleles.bed', 'w') as fh_bed, \
             open(args.output + '.isoalleles.fa', 'w') as fh_fa, \
             open(args.output + '.isoallele.counts.tsv', 'w') as fh_counts:
            fh_map, fh_map_norm = None, None
            if args.generate_map:
                fh_map = open(args.output + '.isoallele.tumor.read.map.txt', 'w')
                if args.iso_read_map_norm is not None:
                    fh_map_norm = open(args.output + '.isoallele.normal.read.map.txt', 'w')
            write_file_header(fh_counts, args.iso_read_map_norm)
            aaseq_to_id = write_out_isoform_allele_groups(iso_allele_to_reads, allele_to_vars, isoforms, gene_to_tot_reads, genome,
                                                          fh_bed, fh_fa, fh_counts, fh_map, fh_map_norm)
            if args.generate_map:
                fh_map.close()
                if args.iso_read_map_norm is not None:
                    fh_map_norm.close()

        make_big_bed(genome, args.output + '.chrom.sizes', args.output + '.isoalleles')
    write_aaseq_key(args.output, aaseq_to_id)
    if args.bam is not None:
        print('labeling bam files')
        label_bam_files(args.bam, args.norm_bam, args.output + '.isoalleles', file_to_read_to_group)


if __name__ == "__main__":
    getvariants()
