"""Read/exon structures and junction utilities, shared across FLAIR modules."""

from collections import namedtuple
from flair import PosRange
from flair.pycbio.hgdata.bed import Bed
from statistics import median
import pysam
import pipettor

BED_FIELDS = [('string', 'chrom', "Reference sequence chromosome or scaffold"),
              ('uint', 'chromStart', "Start position of feature on chromosome"),
              ('uint', 'chromEnd', "End position of feature on chromosome"),
              ('string', 'name', "Name of gene"),
              ('uint', 'score', "Score"),
              ('char[1]', 'strand', "+ or - for strand"),
              ('uint', 'thickStart', "Coding region start"),
              ('uint', 'thickEnd', "Coding region end"),
              ('uint', 'itemRgb', 'An RGB value of the form R,G,B (e.g. 255,0,0)'),
              ('int', 'blockCount', 'The number of blocks (exons) in the BED line'),
              ('int[blockCount]', 'blockSizes', 'A comma-separated list of the block sizes. The number of items in this list should correspond to blockCount'),
              ('int[blockCount]', 'chromStarts', 'A comma-separated list of block starts. All of the blockStart positions should be calculated relative to chromStart. The number of items in this list should correspond to blockCount'),
              ]

EXTRA_BED_FIELDS = [('string', 'gene_id', "unique gene ID generated by FLAIR"),
                    ('string', 'ref_transcript_id', "transcript_id from reference gtf file or generated by FLAIR"),
                    ('string', 'gene_desc', "gene_id from reference gtf file or novel gene region identified by FLAIR"),
                    ('int', 'read_support', "number of full-length reads supporting transcript"),
                    ('float', 'frac_support', "isoform support as fraction of total reads for gene"),
                    ]

POLYA_MIN_FRAC = 0.6
POLYA_SEARCH_WINDOW = 5
POLYA_MIN_LEN = 10
INTPRIM_MIN_FRAC = 0.6
INTPRIM_MIN_AS = 8
INTPRIM_SEARCH_WINDOW = 50

####
# basic types
####
class Junc(PosRange):
    """Splice junction interval (start, end), a type alias for PosRange."""
    pass


class JuncChain(namedtuple("JuncChain", ("chrom", "strand", "juncs"))):
    """A chain of splice junctions on a single chromosome and strand."""

    def __new__(cls, chrom, strand, juncs):
        return super().__new__(cls, chrom, strand, tuple(juncs))

    @classmethod
    def from_exons(cls, chrom, strand, exons):
        """Create a JuncChain from a list of exons."""
        juncs = tuple(Junc(exons[i].end, exons[i + 1].start)
                      for i in range(len(exons) - 1))
        return cls(chrom, strand, juncs)


class Exon(namedtuple("Exon", ("start", "end", "name"))):
    def __new__(cls, start, end, name=None):
        assert start <= end
        if name is None:
            name = ''
        return super(Exon, cls).__new__(cls, start, end, name)

    def __len__(self):
        return self.end - self.start


ISO_SRC_ANNOT = 'annot'
ISO_SRC_NOVEL = 'novel'

def exons_to_juncs(exons):
    """Convert exon ranges to junctions"""
    return [Junc(exons[i].end, exons[i + 1].start)
            for i in range(len(exons) - 1)]


def bed_to_junctions(bed):
    return [Junc(bed.blocks[i - 1].end, bed.blocks[i].start)
            for i in range(1, bed.blockCount)]


def get_rgb(strand, junclen):
    if junclen == 0:
        return "99,99,99"
    elif strand == '+':
        return "27,158,119"
    else:
        return "217,95,2"


def get_bed_exons_from_juncs(juncs, start, end):
    if len(juncs) == 0:
        exon_starts = [0]
        exon_sizes = [end - start]
    else:
        exon_starts = [0] + [j.end - start for j in juncs]
        exon_sizes = ([juncs[0].start - start] + [juncs[i + 1].start - juncs[i].end
                                                  for i in range(len(juncs) - 1)] +
                      [end - juncs[-1].end])
    return exon_starts, exon_sizes


def get_bed_exons_from_exons(exons, start):
    exon_starts = [e.end - start for e in exons]
    exon_sizes = [e.end - e.start for e in exons]
    return exon_starts, exon_sizes


def get_reverse_complement(seq):
    compbase = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C', 'N': 'N',
                'R': 'Y', 'Y': 'R', 'K': 'M', 'M': 'K', 'S': 'S',
                'W': 'W', 'B': 'V', 'V': 'B', 'D': 'H', 'H': 'D'}
    seq = seq.upper()
    new_seq = []
    for base in seq:
        new_seq.append(compbase[base])
    return ''.join(new_seq[::-1])


def get_sequence_for_exons(genome, chrom, strand, exons):
    trans_seq = ''.join([genome.fetch(chrom, e.start, e.end)
                         for e in exons])
    # FIXME: this upper cases only if reverse strand
    if strand == '-':
        trans_seq = get_reverse_complement(trans_seq)
    return trans_seq


def binary_search(query, data):
    """ Query is a coordinate interval. Binary search for the query in sorted data,
        which is a list of coordinates. Finishes when an overlapping value of query and
        data exists and returns the index in data. """
    # FIXME: uses python bisect module
    i = int(round(len(data) / 2))  # binary search prep
    lower, upper = 0, len(data)
    while True:
        if upper - lower < 2:  # stop condition but not necessarily found
            break
        if data[i].end < query.start:
            lower = i
            i = int(round((i + upper) / 2))
        elif data[i].start > query.end:
            upper = i
            i = int(round((lower + i) / 2))
        else:  # found
            break
    return i


def make_big_bed(genome, chrom_sizes_file_name, output_name, output_prefix, my_fields):
    with open(chrom_sizes_file_name, 'w') as fh:
        for chrom in genome.references:
            fh.write(chrom + '\t' + str(genome.get_reference_length(chrom)) + '\n')
    write_as_file(my_fields, output_prefix + '.as', output_name.replace('-', '').replace('.', ''), f'FLAIR isoforms for {output_name}')
    pipettor.run([('bedToBigBed', f'-as={output_prefix}.as', '-type=bed12+', f'{output_prefix}.bed', chrom_sizes_file_name, f'{output_prefix}.bb', '-sort')])

def write_as_file(fields, filename, tablename, description):
    with open(filename, 'w') as as_fh:
        as_fh.write(f'table {tablename}\n"{description}"\n(\n')
        for field in fields:
            as_fh.write(field[0] + '\t' + field[1] + ';\t"' + field[2] + '"\n')
        as_fh.write(')')

def convert_to_bed(readrec, extraCols=None):
    """Create and return a Bed object."""
    if extraCols is None:
        extraCols = []
    else:
        extraCols = [readrec.__dict__[x] for x in extraCols]
    exon_starts, exon_sizes = get_bed_exons_from_juncs(readrec.juncs, readrec.start, readrec.end)
    bed = Bed(readrec.chrom, readrec.start, readrec.end, readrec.name,
              score=readrec.score, strand=readrec.strand,
              thickStart=readrec.start, thickEnd=readrec.end,
              itemRgb=get_rgb(readrec.strand, len(readrec.juncs)), extraCols=extraCols)
    for i in range(len(exon_starts)):
        blk_start = readrec.start + exon_starts[i]
        bed.addBlock(blk_start, blk_start + exon_sizes[i])
    return bed

def get_exons(readrec):
    """Return exons as list of Exon objects, computed from start, end, and juncs."""
    if not readrec.juncs:
        return [Exon(readrec.start, readrec.end)]
    exons = [Exon(readrec.start, readrec.juncs[0].start)]
    for i in range(len(readrec.juncs) - 1):
        exons.append(Exon(readrec.juncs[i].end, readrec.juncs[i + 1].start))
    exons.append(Exon(readrec.juncs[-1].end, readrec.end))
    return exons


def check_intprim(end_seq):
    i = 10
    while i < len(end_seq) and end_seq[:i].count('A') / i >= INTPRIM_MIN_FRAC:
        i += 1
    j = end_seq[:i].count('A')
    if j < INTPRIM_MIN_AS or j / i < INTPRIM_MIN_FRAC:
        return 0
    else:
        return j

def _check_poly_base(end_seq, base):
    """Check for a poly-base run using a rolling window."""
    if len(end_seq) < POLYA_SEARCH_WINDOW:
        return 0
    i = POLYA_SEARCH_WINDOW
    while i < len(end_seq) and end_seq[i - POLYA_SEARCH_WINDOW:i].count(base) / POLYA_SEARCH_WINDOW >= POLYA_MIN_FRAC:
        i += 1
    j = end_seq[:i].rfind(base) + 1
    if j < POLYA_MIN_LEN:
        return 0
    return j


def check_polyA(end_seq):
    return _check_poly_base(end_seq, 'A')


def check_polyT(end_seq):
    return _check_poly_base(end_seq, 'T')


class ReadRec:
    """Read alignment with location, junction, and metadata fields.

    Stores chrom, start, end, name, score, strand, and juncs directly.
    Exons are computed on the fly from start, end, and juncs.
    A Bed record can be produced on demand via to_bed().

    Junction tuples are interned via a class-level cache so identical junction
    chains share a single tuple object.
    """

    # keep on one copy of junction chain
    _juncs_cache = {}

    @classmethod
    def _intern_juncs(cls, juncs):
        return cls._juncs_cache.setdefault(juncs, juncs)

    def __init__(self, chrom, strand, juncs, start, end, name, *, score=None, polyA=None, intprim=None):
        self.chrom = chrom
        self.strand = strand
        self.juncs = self._intern_juncs(juncs)
        self.start = start
        self.end = end
        self.name = name
        self.score = score
        self.polyA = polyA  # (left int, right int)
        self.intprim = intprim  # (left int, right int)

    @property
    def exons(self):
        return get_exons(self)

    def reset_from_exons(self, exons):
        """Update ReadRec from a list of Exon objects."""
        self.start = exons[0].start
        self.end = exons[-1].end
        self.juncs = tuple(exons_to_juncs(sorted(exons)))

    def correct_from_annotation(self, start, end, strand, juncs):
        """Update ReadRec with corrected coordinates from annotation match."""
        self.start = start
        self.end = end
        self.strand = strand
        self.juncs = tuple(juncs)

    def _get_both_intprim(read, genome):
        left_intprim, right_intprim = 0, 0
        if read.reference_start > INTPRIM_SEARCH_WINDOW:
            end_seq = get_reverse_complement(genome.fetch(read.reference_name, read.reference_start - INTPRIM_SEARCH_WINDOW, read.reference_start))
            left_intprim = check_intprim(end_seq)
        if read.reference_end + INTPRIM_SEARCH_WINDOW < genome.get_reference_length(read.reference_name):
            end_seq = genome.fetch(read.reference_name, read.reference_end, read.reference_end + INTPRIM_SEARCH_WINDOW).upper()
            right_intprim = check_intprim(end_seq)
        return left_intprim, right_intprim

    def _detect_poly_tails(read):
        """Detect polyA/polyT tails in soft-clipped ends.

        Returns (left_polyA, right_polyA) where:
        - left_polyA > 0: poly-tail at left end (- strand indicator)
        - right_polyA > 0: poly-tail at right end (+ strand indicator)

        Both polyA and polyT are checked on each end to handle cDNA reads
        where the antisense strand has polyT instead of polyA.  Both indicate
        the location of the mRNA 3' end.

        The check functions expect the tail at the start of the sequence.
        Right clips already have this orientation; left clips are reversed.
        """
        left_polyA, right_polyA = 0, 0
        read_seq = read.query_sequence
        if read.cigartuples[0][0] == pysam.CIGAR_OPS.CSOFT_CLIP:
            left_rev = read_seq[:read.cigartuples[0][1]][::-1]
            left_polyA = max(check_polyA(left_rev), check_polyT(left_rev))
        if read.cigartuples[-1][0] == pysam.CIGAR_OPS.CSOFT_CLIP:
            right_seq = read_seq[-1 * read.cigartuples[-1][1]:]
            right_polyA = max(check_polyA(right_seq), check_polyT(right_seq))
        return left_polyA, right_polyA

    @classmethod
    def from_read(cls, read, junc_direction=None, *, genome=None):
        """Create a ReadRec from a pysam aligned read."""
        # FIXME switch to pycbio.hgdata.cigar
        align_start = read.reference_start
        ref_pos = align_start
        intron_blocks = []
        has_match = False
        for block in read.cigartuples:
            if block[0] == pysam.CIGAR_OPS.CREF_SKIP:  # intron
                if has_match:
                    intron_blocks.append([ref_pos, ref_pos + block[1]])
                # this fixes weird bug if there's an intron, then an insertion, then another intron???
                elif len(intron_blocks) > 0:
                    intron_blocks[-1][1] += block[1]
                has_match = False
                ref_pos += block[1]
            elif block[0] in (pysam.CIGAR_OPS.CMATCH, pysam.CIGAR_OPS.CEQUAL, pysam.CIGAR_OPS.CDIFF, pysam.CIGAR_OPS.CDEL):  # consumes reference
                ref_pos += block[1]
                if block[0] in (pysam.CIGAR_OPS.CMATCH, pysam.CIGAR_OPS.CEQUAL, pysam.CIGAR_OPS.CDIFF):
                    has_match = True
        if junc_direction not in {'+', '-'}:
            junc_direction = "-" if read.is_reverse else "+"
        juncs = tuple(Junc(blk[0], blk[1]) for blk in intron_blocks)
        left_polyA, right_polyA = cls._detect_poly_tails(read)
        left_intprim, right_intprim = 0, 0
        if genome is not None:
            left_intprim, right_intprim = cls._get_both_intprim(read, genome)

        return cls(read.reference_name, junc_direction, juncs, align_start, ref_pos, read.query_name, polyA=(left_polyA, right_polyA), intprim=(left_intprim, right_intprim))


class Gene:
    """A gene containing discovered isoforms."""

    def __init__(self, gene_id, gene_desc, chrom, strand):
        self.gene_id = gene_id
        self.gene_desc = gene_desc
        self.chrom = chrom
        self.strand = strand
        self.isoforms = []

    def add_isoform(self, isoform):
        """Add an isoform to this gene and set the back-reference."""
        self.isoforms.append(isoform)
        isoform.gene = self
        isoform.gene_id = self.gene_id


class Isoform:
    # keep on one copy of junction chain
    _juncs_cache = {}

    @classmethod
    def _intern_juncs(cls, juncs):
        return cls._juncs_cache.setdefault(juncs, juncs)

    def __init__(self, chrom, strand, juncs, start=None, end=None, reads=None, gene=None, gene_id=None, ref_transcript_id=None):
        self.chrom = chrom
        self.strand = strand
        self.juncs = self._intern_juncs(juncs)
        self.start = start
        self.end = end
        self._name = None
        self._score = None
        self.reads = reads if reads is not None else []
        self.gene = gene
        self.gene_id = gene_id
        self.ref_transcript_id = ref_transcript_id
        self.end5confidence = None
        self.end3confidence = None

    @property
    def name(self):
        # FIXME: ideally would add chromosome and strand to this hash
        # FIXME: start none might not be the best trigger.
        # if self._name is None:
        if self.start is None:
            return str(abs(hash(tuple(self.juncs))))
        else:
            return str(abs(hash(tuple(self.exons))))
        # else:
        #     return self._name

    @name.setter
    def name(self, new_name):
        self._name = new_name

    @property
    def exons(self):
        if self.start is None:
            self.start = int(median(self.starts))
            self.end = int(median(self.ends))
        return get_exons(self)

    @property
    def starts(self):
        return [x.start for x in self.reads]

    @property
    def ends(self):
        return [x.end for x in self.reads]

    @property
    def num_reads(self):
        return len(self.reads)

    @property
    def score(self):
        if self._score is None:
            return len(self.reads)
        else:
            return self._score

    @score.setter
    def score(self, new_score):
        self._score = new_score

    @property
    def genomic_length(self):
        if self.start is None or self.end is None:
            return None
        return self.end - self.start

    def reset_from_exons(self, exons):
        """Update Isoform from a list of Exon objects."""
        self.start = exons[0].start
        self.end = exons[-1].end
        self.juncs = tuple(exons_to_juncs(sorted(exons)))

    def get_sequence(self, genome):
        if self.start is None or self.end is None:
            return None
        return get_sequence_for_exons(genome, self.chrom, self.strand, self.exons)

    @classmethod
    def from_readrec(cls, readrec):
        return cls(readrec.chrom, readrec.strand, readrec.juncs)

    @classmethod
    def regroup(cls, iso, newstart=None, newend=None, newreads=[], newstrand=None):
        """Create a new Isoform by regrouping reads from an existing one."""
        if newstrand is None:
            newstrand = iso.strand
        return cls(iso.chrom, newstrand, iso.juncs, newstart, newend, newreads, iso.gene, iso.gene_id, iso.ref_transcript_id)
