# Copyright 2006-2025 Mark Diekhans
"""TSV reading classes"""
import sys
import csv
from flair.pycbio.sys import fileOps
from flair.pycbio.tsv.tsvRow import TsvRow
from flair.pycbio.tsv import TsvError
from flair.pycbio.tsv.tsvColumns import columnsSpecBuild

csv.field_size_limit(sys.maxsize)


# typeMap converter for str types where empty represents None
strOrNoneType = (lambda v: None if (v == "") else v,
                 lambda v: "" if (v is None) else v)

# typeMap converter for int types where empty represents None
intOrNoneType = (lambda v: None if (v == "") else int(v),
                 lambda v: "" if (v is None) else str(v))

# typeMap converter for float types where empty represents None
floatOrNoneType = (lambda v: None if (v == "") else float(v),
                   lambda v: "" if (v is None) else str(v))


class printf_basic_dialect(csv.Dialect):
    """Describes the usual properties for TSV files generated by printf, etc.
    Quotes can be included in data, etc.
    """
    delimiter = '\t'
    quotechar = None
    doublequote = False
    skipinitialspace = False
    lineterminator = '\n'
    quoting = csv.QUOTE_NONE

def _dehashHeader(row):
    if (len(row) > 0) and row[0].startswith('#'):
        # sometimes there is a space after #
        row[0] = row[0][1:].strip()


class TsvReader:
    """Class for reading TSV files.  Reads header and builds column name to
    column index map.  Iterating yields TsvRow objects (or custom rowClass)
    with columns accessible as attributes.  Columns can be automatically
    type-converted via typeMap.

    If the first character of the header is '#', the '#' and following spaces
    are ignored and not part of the first column name.

    Can be used as a context manager.
    """

    def __init__(self, fileName, *, rowClass=None, typeMap=None, defaultColType=None,
                 columns=None, columnNameMapper=None, ignoreExtraCols=False,
                 inFh=None, allowEmpty=False, dialect=csv.excel_tab,
                 encoding=None, errors=None):
        """
        Open TSV file and read header into object. Removes leading '#' from
        UCSC-style headers.

        :param fileName: Path to the TSV file, unless `inFh` is provided.
        :param rowClass: Class or factory to construct a row. Called with the
            TsvReader instance and a list of string column values.
        :param typeMap: Dictionary mapping column names to either a type or a
            (parseFunc, formatFunc) tuple. Unlisted columns are left as strings.
            If `columnNameMapper` is used, the keys should be mapped names.
        :param defaultColType: Type to use for columns not listed in `typeMap`.
        :param columns: List of column names to use if no header is present in
            the file.
        :param columnNameMapper: Function to map raw column names to internal
            names before applying `typeMap`.
        :param ignoreExtraCols: If True, extra columns in rows are ignored.
        :param inFh: An open file-like object to read from instead of `fileName`.
            It will not be closed automatically.
        :param allowEmpty: If True, treat empty input as EOF rather than error.
        :param dialect: A `csv.Dialect` instance or dialect name.
        :param encoding: Optional text encoding (e.g., 'utf-8').
        :param errors: Optional error handling strategy (e.g., 'strict',
            'replace', 'ignore').
        """
        self.fileName = fileName
        self.inFh = None
        self._shouldClose = False
        self._reader = None
        self.rowClass = rowClass
        if rowClass is None:
            self.rowClass = TsvRow
        self.ignoreExtraCols = ignoreExtraCols
        try:
            self._openTsv(fileName, inFh, dialect, encoding, errors)
        except Exception as ex:
            self.close()
            raise TsvError(f"open of TSV failed {fileName}") from ex

        if columns is None:
            columns = self._readHeader(allowEmpty)
        self.columnSpecs = columnsSpecBuild(columns, typeMap, defaultColType, columnNameMapper)

    @property
    def columns(self):
        "column names"
        return self.columnSpecs.columns

    def _openTsv(self, fileName, inFh, dialect, encoding, errors):
        if inFh is not None:
            self.inFh = inFh
            self._shouldClose = False
        else:
            self.inFh = fileOps.opengz(fileName, encoding=encoding, errors=errors)
            self._shouldClose = True
        self._reader = csv.reader(self.inFh, dialect=dialect)

    def close(self):
        """Close the file if this object opened it."""
        if self._shouldClose and self.inFh is not None:
            self.inFh.close()
            self.inFh = None

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()

    @property
    def lineNum(self):
        return self._reader.line_num

    def _readHeader(self, allowEmpty):
        try:
            row = next(self._reader)
            _dehashHeader(row)
            return row
        except StopIteration:
            if not allowEmpty:
                raise TsvError("empty TSV file", reader=self)
            return []

    def _parseColumnWithTypeMap(self, row, iCol):
        ct = self.columnSpecs.types[iCol]
        cv = ct[0] if isinstance(ct, tuple) else ct
        try:
            # can be None to have formatter but not parser
            if cv is not None:
                row[iCol] = cv(row[iCol])
        except Exception as ex:
            raise TsvError(f"Error converting TSV column {iCol} ({self.columns[iCol]}) to object, value \"{row[iCol]}\"") from ex

    def _parseColumns(self, row):
        "converts columns in row in-place, if needed"
        for iCol in range(len(self.columnSpecs.columns)):
            self._parseColumnWithTypeMap(row, iCol)

    def _constructRow(self, row):
        if self.ignoreExtraCols:
            if len(row) < len(self.columns):
                raise TsvError(f"row has {len(row)} columns, expected at least {len(self.columns)}", reader=self)
        else:
            if len(row) != len(self.columns):
                raise TsvError(f"row has {len(row)} columns, expected exactly {len(self.columns)}", reader=self)

        try:
            if self.columnSpecs.types is not None:
                self._parseColumns(row)
            return self.rowClass(self, row)
        except Exception as ex:
            raise TsvError("Error converting TSV row to object", self) from ex

    def __iter__(self):
        try:
            for row in self._reader:
                yield self._constructRow(row)
        except Exception as ex:
            raise TsvError("Error reading TSV row", self) from ex
        finally:
            self.close()

    def formatRow(self, row):
        "format row to a list of strings given specified types"
        return self.columnSpecs.formatRow(row)
